micronaut:
  application:
    name: reactjs
mongodb.uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}

myappConfig:
  mongo:
    databaseName: ${MONGO_DB_NAME:myapp}